xunit/xunit

src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs
When Task.Factory.StartNew(...), Task.ContinueWith(...), etc. are used without specifying a TaskScheduler, TaskScheduler.Current is used.  Since tests are being scheduled to a TaskScheduler that wraps the MaxConcurrencySyncContext, that means that if a test itself schedules another task using one of these methods without specifying a scheduler, that task will be scheduled back to the same MaxConcurrencySyncContext.  In some cases that isn't problematic; however, if a synchronous test schedules such a task and then synchronously blocks waiting for such a task to complete, it's possible for the test to deadlock, e.g. if the concurrency level is 1 such that there's only one worker and that worker is blocked in the test waiting for the queued task to complete, but the queued task will never …
=> Schedule tasks with TaskCreationOptions.HideScheduler

src/common/XmlTestExecutionVisitor.cs, test/test.xunit.execution/Common/XmlTestExecutionVisitorTests.cs
When tests are running asynchronously and some of them change the thread culture during the test this results in number format issues in the xml document. Some of the numbers are formatted with periods as the decimal point and others have commas.
The fix is to add CultureInfo.InvariantCulture to all the ToString calls.
=> Add InvariantCulture to xml output formatting.

src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestInvokerTests.cs
As discussed (https://github.com/xunit/xunit/commit/d376e851f724fc70a86634fa36522696443b9087#commitcomment-10286397).
I think this is probably a typo.
I'm not sure if you have any appetite to change this now since strictly speaking it's a breaking change to the API. On other hand, chances are low anyone's using it yet. After recent changes, I'm no longer using it in xbehave.
Anyway, here it is, FWIW.
=> change TestInvoker.InvokeTestMethodAsync from public to protected

build.sh
Changed hardcoded bash shebang to env to support multiple directory
structures (required to build on FreeBSD).
=> build: Enables FreeBSD support

src/xunit.assert/Asserts/CollectionAsserts.cs, src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs, src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs, src/xunit.execution.desktop/Sdk/LongLivedMarshalByRefObject.cs, src/xunit.runner.utility.desktop/Utility/LongLivedMarshalByRefObject.cs, test/test.xunit.assert/Asserts/CollectionAssertsTests.cs, test/test.xunit.execution/Common/XmlTestExecutionVisitorTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/TestCaseRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/TestRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscovererTests.cs, test/test.xunit.runner.reporters/TeamCityReporterMessageHandlerTests.cs, test/test.xunit.runner.tdnet/Visitors/ResultVisitorTests.cs, test/test.xunit.runner.utility/Extensibility/DefaultRunnerReporterMessageHandlerTests.cs
as discussed in https://github.com/xunit/xunit/issues/623 this PR replaces occurrences of String by string and Object by object where appropriate.
Does not change any functionality, nor does it change any other code style or something like that.
=> code cleanup: replace Object by object and String by string.

src/xunit.runner.msbuild/xunit.cs
MSBuild runner modification - Added an IgnoreFailures parameter.  If IgnoreFailures is set true then the Execute function will return true if there are test failures.  This allows for better integration with TeamCity since it will allow you to use the Mute Test feature to Mute failing tests.
=> Fix for #605 - MSBuild Runner add an IgnoreFailures parameter.

test/test.xunit.runner.utility/Extensibility/DefaultRunnerReporterMessageHandlerTests.cs
Two tests were failing on my machine because my default culture is different from English (in class OnMessage_ITestExecutionSummary). Here comma is used instead of dot as a decimal separator. So I had "Time: 1,235s" instead of "Time: 1.235s".
I applied CulturedFact attribute to these tests. Now they pass on my machine.
=> Fix of tests failing depending of culture using CulturedFact attribute

src/xunit.console/Utility/TransformFactory.cs
This allows xunit process to run in parallel without contending for access to the transform file.
closes #656
=> Use FileShare.Read when opening transform files

test/test.xunit.execution/Acceptance/Xunit2AcceptanceTests.cs, test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/TestAssemblyRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/TestClassRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunnerTests.cs, test/test.xunit.execution/Sdk/TestFrameworkProxyTests.cs, test/test.xunit.runner.utility/Extensibility/DefaultRunnerReporterMessageHandlerTests.cs, test/test.xunit.runner.utility/Frameworks/v1/Xunit1ExceptionUtilityTests.cs, test/test.xunit.runner.utility/Frameworks/v1/Xunit1Tests.cs, test/test.xunit.runner.utility/Utility/ExceptionUtilityTests.cs
This pull requests fixes some of the errors reported in issue #616.
It's fixed here for all tests where the expected exceptions are thrown in the same thread the test method starts in.
reduces the number of failing tests (in my German Windows 10 environment) from 29 to 13 without changing any functionality.
=> fixing some affected tests of #616 by defining the culture of test environment

src/xunit.assert.nuspec, src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs, src/xunit.core.nuspec, test/test.xunit.assert/Asserts/CollectionAssertsTests.cs
Issue #240 
It was a little tricky checking whether the type implements `ISet` as there is no non generic `ISet` (as opposed to `IDictionary`).
I added the `ObjectEqualityComparerAdapter` class to be able to use the innerComparer if there is one and I couldn't use the `DefaultInnerComparer` since `AssertEqualityComparerAdapter` doesn't implement `GetHashCode`. Although, I couldn't find a way to pass a custom inner comparer (opened a suggestion - issue #640).
=> Refactor AssertEqualityComparer to handle sets

CONTRIBUTING.md
The governance link was linking relative to the GitHub repo, rather than to the (separate) `xunit.github.io` domain.
=> Fix governance link

build.sh
The `build.sh` file is updated to use the latest NuGet.exe, which fixes the build.
For the relevant NuGet issue, see: https://github.com/NuGet/Home/issues/1543.
=> Use latest NuGet.exe file for Linux/Mac builds. References #607

src/xunit.core/AssemblyTraitAttribute.cs, src/xunit.core/Sdk/AssemblyTraitDiscoverer.cs, src/xunit.core/xunit.core.csproj, src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs, test/GlobalTestAssemblyInfo.cs, test/test.xunit.execution/Sdk/Frameworks/XunitTestCaseTests.cs, test/test.xunit.execution/Sdk/TestCaseSerializerTests.cs
This is the implementation of Issue #211. Another possible solution: do not create separate AssemblyTrait attribute, but allow existing Trait attribute to be set on assembly.
=> Issue#211. Apply TraitAttribute to whole assembly

src/xunit.core/ClassDataAttribute.cs, src/xunit.core/MemberDataAttribute.cs, src/xunit.core/MemberDataAttributeBase.cs, src/xunit.core/Sdk/DataAttribute.cs
make clear in the documentation that MemberDataAttribute should not return the same objects twice.
=> better documentation to avoid issue #695

src/xunit.execution/Sdk/Reflection/Reflector.cs
Fixes https://github.com/xunit/xunit/issues/841
In cases where there are assignable types passed in, this could would still attempt to convert them by calling Convert.ChangeType.  This method throws when 'arg' is not IConvertible.
=> Do not attempt to unnecessarily convert types which are compatible.

src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs
Which means it doesn't always do enough concurrency... Fixes #877. I did a little perf testing out of curiosity, but didn't see any measurable perf difference for this [in the ordinary case the bug probably isn't hit].
=> Fix race condition in MaxConcurrencySyncContext

src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs
I've been seeing this error a few times during test runs, running 2.1:
System.NullReferenceException: Object reference not set to an instance of an object.
at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 150
The offender is the default constructor for tuples in .Net 4.0+ - default(Tuple<T1, T2>) returns null. If the InvokeTestAsync function above raises, this is what is returned by RunAsync and hence we see a NullReferenceException.
=> Add null check for tuple

src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs, src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs, test/test.xunit.execution/Acceptance/FixtureAcceptanceTests.cs
Fixes #869
IAsyncLifetime fixtures both class fixtures and in collections are only
initialized once.
All async initialization and disposal is now executed concurrently.
=> Stop repeated initialization of async fixtures

src/xunit.console/App.config
This seems to occur when running tests that reference and invoke an assembly that was built on .NET 2.0 (or used SGEN?). In our case it was the SMO (SQL Server Management Objects) library. This commit adds the useLegacyV2RuntimeActivationPolicy attribute for the console runner and sets it to true.
_NB: Not sure how this affects test assemblies that don't require this runtime attribute :(_
```
System.IO.FileLoadException : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
Stack Trace:
at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
at …
```
=> Fix 'Mixed mode assembly is built against version 'v2.0.50727' of the runtime' error (console runner)

src/xunit.runner.utility/Utility/DiaSession.cs, src/xunit.runner.utility/Utility/DiaSessionWrapper.cs, src/xunit.runner.utility/Utility/DiaSessionWrapperHelper.cs
In the Visual Studio runner, test source information is provided using `VisualStudioSourceInformationProvider`. VS uses this information to group tests by project, to jump to the source of tests and to run tests from a context menu. However, the provider is returning null for inherited test cases in referenced projects. These tests show up as category External" and IDE features don't work for them. The problem can be seen in the following solution:
https://github.com/gulbanana/xunit-repro
This PR updates the DiaSession wrapper to inspect the assembly associated with individual test class types instead of assuming all test cases are in the same assembly. It shouldn't have performance implications as it will only produce one extra session wrapper per assembly that contains discovered tests. …
=> Provide source information for referenced assemblies, fixing test categorisation

src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs
Tests with async logging can cause a IndexOutOfBoundsException because the TestOutputHelper.Output getter does not lock the internal StringBuilder. This commit locks the getter with the pre-existing lockObject.
=> Added lock around TestOutputHelper getter.

src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs
Currently it feels a little confusing, because the type is given an `ITest`, and "test" and "test case" seem to be two distinct concepts in the internal language.
=> correct "test case" in TestOutputHelper to "test"

test/test.xunit.runner.msbuild/xunitTests.cs
Fixes tests running on my laptop vs desktop
@bradwilson
=> Fix a test that relies on the TEMP environment variable ending in '/'

src/xunit.core/Sdk/DataDiscoverer.cs, test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs
As suggested by @stephentoub in dotnet/corefx#11017
```
public abstract class BaseClassWithTestWithoutData
{
[Theory]
[MemberData("TestData")]
public void Test(int data) { }
}
public class SubClassWithTestData : BaseClassWithTestWithoutData
{
public static IEnumerable<object[]> TestData()
{
yield return new object[] { 42 };
}
}
```
=> Add support for MemberData referring to a method in a sub type from a test in a base type

src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs
- Don't use linq: 7x faster according to my benchmarks
- Cache the result
This saves two array allocations and an Array.Copy call in `MethodInfo.GetParameters()`
=> Improve perf and allocations of GetParameters

src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs, test/test.xunit.execution/Sdk/ArgumentFormatterTests.cs, test/test.xunit.execution/Sdk/TestOutputHelperTests.cs
Fixes #876
@gigi81 and @edumunoz FYI
=> Fix TestOutputHelper crashing on invalid xml chars

src/xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunner.cs, src/xunit.execution/Sdk/Frameworks/TheoryDiscoverer.cs, test/test.xunit.execution/Sdk/Frameworks/TheoryDiscovererTests.cs
=> Fix NullReferenceException if IDataDiscoverer.GetData returns null

src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs, src/xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunner.cs, src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs, src/xunit.execution/Sdk/TypeUtility.cs, test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs
Fixes #945
Fixes #763
I also changed the TypeUtility method (I presume you made it public, right?) to be an extension method, to be consistent with the other methods in the class.
Allows the following tests (see the tests added for more details):
```
[Theory]
[InlineData()]
[InlineData(null)]
[InlineData(1)]
[InlineData(new object[] { new object[] { 1 } })]
[InlineData(new int[] { 1 })]
[InlineData(1, 2, 3, 4, 5, 6)]
public void ParamsObjectTest(params object[] array) {}
```
@klimcio and @Serg046 FYI
=> Add support for params arrays in test methods

src/xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunner.cs, src/xunit.execution/Sdk/Frameworks/TheoryDiscoverer.cs, test/test.xunit.execution/Sdk/Frameworks/TheoryDiscovererTests.cs
Fixes xunit#839
- DataDiscoverer doesn't exist
- DataDiscoverer is not an IDataDiscoverer
@citizenmatt FYI
=> Fix obfuscated ArgumentNullException thrown when a DataDiscoverer does not exist

test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs
Add tests for #1040, looks like it doesn't reproduce.
Closes #1040
=> Add tests for async task method with multiple inline data attributes

src/xunit.execution/Sdk/TypeUtility.cs
This is necessary to avoid a breaking change in the future when we release.
This is becasue I'm working on resolving arguments for ConstructorInfos
=> Make TypeUtility.ResolveMethodArguments use MethodBase instead of MethodInfo

src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs, src/xunit.execution/Sdk/TypeUtility.cs, test/test.xunit.execution/Acceptance/FixtureAcceptanceTests.cs
Fixes #985
TypeUtility.GetDefaultValue(this TypeInfo typeInfo) will be used elsewhere in a subsequent PR
=> Add support for optional, default and params parameters in test fixtures

src/xunit.runner.reporters/JsonExtentions.cs, test/test.xunit.runner.reporters/JsonExtensionsTests.cs
Fix incorrect escaping of quotes for encoding strings as JSON due to one too many slashes being added.
Resolves #1116.
=> Fix incorrect JSON encoding

src/xunit.core/TheoryData.cs
As mentioned in #1173, there are two typos in the `TheoryData` docs with 4 and 5 types.
Fixes #1173
=> Fix typos in constructor summary for TheoryData

src/dotnet-xunit/Program.cs
This closes #1212 .
This is just an initial stab at the solution.  Feedback is welcome.
`dotnet xunit -internaldiagnostics`
```
Running desktop CLR tests for framework net452...
EXEC: "mono64" "/Users/jimmy/.nuget/packages/dotnet-xunit/2.3.0-jimmy001/tools/net452/xunit.console.exe" "MyCoolNewLib.Tests.dll" -internaldiagnostics
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
Discovering: MyCoolNewLib.Tests
Discovered:  MyCoolNewLib.Tests
Starting:    MyCoolNewLib.Tests
Finished:    MyCoolNewLib.Tests
=== TEST EXECUTION SUMMARY ===
MyCoolNewLib.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.109s
```
`dotnet xunit -internaldiagnostics -x86`
```
Running desktop CLR tests for framework net452...
EXEC: "mono" …
```
=> Issue #1212 - use mono with dotnet-xunit if not on windows

src/dotnet-xunit/MsBuild.cs, src/dotnet-xunit/Program.cs
`dotnet xunit` needs to run an msbuild build in order to discover project information. Right now this uses `dotnet msbuild`, which can't build all project types. With this PR, a flag can be used by people with a full-framework msbuild on their `%PATH%` to support, for example, using dotnet xunit to test a UWP class library.
=> dotnet-xunit: add -usemsbuild flag 

src/xunit.execution/Sdk/Frameworks/FactDiscoverer.cs, src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs, src/xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunner.cs, src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs, src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs
This pull request is a non-functional change to Xunit. It aims to provide fine-grained access to test case creation, test discovery and test runners so that when writing 3rd party libraries, sub-classing can be used to provide additional control over the test execution process.
=> Add extensibility points

src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs, src/xunit.execution/Sdk/TypeUtility.cs
1) Adding MethodGenericTypes to the hash, to ensure that distinct UniqueIDs are generated for generic method tests that only differ by a type parameter.
2) Using an assembly name string that does not include version info, to make these UniqueIDs consistent across assembly version bumps.  This makes the UniqueID more useful for correlating results for the same test over time.
=> 2 Modifications to GetUniqueID

src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs, test/test.xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscovererTests.cs
Resolves #1068 
Issue: When trying to find base method for `CustomAttributeData`, we checked base type of method's declaring type to find matching base method but if the base type did not define the method, we returned null. In multiple level of hierarchy (`GrandParent` -> `Parent` -> `Child`), if the method is overridden in `Child` class without `FactAttribute` on it (assuming it would be carried from the base method), we would try to find base method on `Parent` Class. But if the method is defined on `GrandParent` and not overridden in `Parent` class then we will not be able to locate the base method hence associated `CustomAttributeData` is not found which causes test to be ignored.
Fix is to go multiple levels towards base till we find base method.
=> Traverse multiple levels in hierarchy to find base method info

src/xunit.runner.visualstudio/Utility/RunSettingsHelper.cs, src/xunit.runner.visualstudio/VsTestRunner.cs, test/test.xunit.runner.visualstudio/RunSettingsHelperTests.cs
Refer RFC: https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0010-Source-Information-For-Discovered-Tests.md
Summary:
CollectSourceInformation = True => Test adapter needs to collect source information for the discovered tests
CollectSourceInformation = False => Test adapter doesn't need to collect source information for discovered tests. In case tests are executed from VS IDE, then Test Window will get this information using Roslyn.
By default CollectSourceInformation will be true. It will be false when:
1. VS IDE determines that it can get this information from Roslyn
2. Command line scenario: When tests are executed from vstest.console.exe, this flag will always be false unless user explicitly overrides it in the runsettings XML file.
=> Added functionality to honor CollectSourceInformation flag from RunSettings XML

src/xunit.runner.visualstudio/Constants.cs, src/xunit.runner.visualstudio/Utility/RunSettingsHelper.cs, src/xunit.runner.visualstudio/VsTestRunner.cs, test/test.xunit.runner.visualstudio/RunSettingsHelperTests.cs
This change allows an adapter to bail out if it's loaded in incorrect target runtime. It can happen if .NET core adapter is loaded to run a desktop test for instance (this occurs consistently if user has .NET 4.7 installed).
Provide different executor URI identifiers for the desktop and dotnet core adapters.
Fixes #1348.
=> Checks for target runtime before discovery/execution

src/xunit.core/CollectionAttribute.cs, src/xunit.core/CollectionDefinitionAttribute.cs, src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs, test/test.xunit.execution/Acceptance/Xunit2AcceptanceTests.cs
This spawned [from a Twitter discussion here](https://twitter.com/Nick_Craver/status/897515667259359234).
In every one of our libraries, especially with settings, event handlers, etc. some tests just aren't friendly with parallelization. We want parallel testing in the vast majority of cases (that can in itself reveal issues), but specific tests (or collections) we want to run non-parallel separately from everything else.
This change allows a `CollectionDefinition` to specify `DisableParallelization = true` to support this. The behavior is: all parallel collections (any not specifying this new constructor argument specifically) run first and in parallel (no behavior change from today). Then any collections specifying `DisableParallelization = true` are run, each is awaited in order. This …
=> Feature: Add CollectionDefinition.DisableParallelization

src/common/ConcurrentDictionary.cs, src/common/SerializationHelper.cs, src/xunit.runner.utility/xunit.runner.utility.csproj, src/xunit.runner.visualstudio/Sinks/VsDiscoverySink.cs, src/xunit.runner.visualstudio/VsTestRunner.cs
This PR does two things based on some profiling
1. batches cross-appdomains calls to the serializer based on test-class instead of method. 
2. Caches `Type` to `string` in the `SerializationHelper` since those lookups were expensive. I ported a `ConcurrentDictionary` from the old TPL that's .NET 3.5-friendly for the NET 3.5 runner utility.
In my "wall time" of running 10k unit test discovery (from the `perf-tests` branch), these changes make the .NET 4.5.2 version go from approx. 30 sec to about 12 sec. Still a long time, but better.
The one downside is that with the current batching technique, there's a pause before users see output since it's not sending them over till it's done with the test class, and this pathological test has 10k tests in a single test class.
/cc @benaadams
=> Performance improvements around serialization

src/xunit.console/CommandLine.cs, test/test.xunit.console/CommandLineTests.cs
Added a method to make sure the file path exists after the following twitter thread: https://twitter.com/xunit/status/904718357697630213
=> Make sure output file full path exsits

xunit.vs2017.sln
`build.sh` was removed in 914e97d57e388b5c8c2bf5c4381b5c232ed64b5a:
```
commit 914e97d57e388b5c8c2bf5c4381b5c232ed64b5a
Author: Brad Wilson <dotnetguy@gmail.com>
Date:   Tue Mar 14 00:03:09 2017 -0700
Update build to Powershell, add support for AppVeyor
.gitignore    |  42 ++++++------
appveyor.yml  |  41 ++++++++++++
build.ps1     | 204 ++++++++++++++++++++++++++++++++++++++++++++++++++++------
build.sh      |  66 -------------------
xunit.msbuild | 187 -----------------------------------------------------
5 files changed, 248 insertions(+), 292 deletions(-)
```
However, the Visual Studio solution still contained a reference and which is what this PR removes.
=> Remove deleted build.sh from VS solution

test/test.utility/CultureAwareTesting/CulturedXunitTheoryTestCaseRunner.cs
`originalUICulture` is checked for null in both if statements making them identical.
=> Same variable checked twice for null

test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
`IEquatableActual_Explicit_NotEqual` and `IComparableActual_Explicit_NotEqual` tests `ImplicitIEquatableExpected` instead of `ExplicitIEquatableExpected`.
=> ImplicitIEquatableExpected tested instead of ExplicitIEquatableExpected

test/test.xunit1/xunit.extensions/FreezeClock/ClockFacts.cs, test/test.xunit1/xunit.extensions/FreezeClock/FreezeClockAttributeAcceptanceTests.cs, test/test.xunit1/xunit.extensions/FreezeClock/FreezeClockAttributeFacts.cs
[`Milliseconds`](https://msdn.microsoft.com/en-us/library/system.timespan.milliseconds(v=vs.110).aspx) ranges from -999 to 999, so checking for `Milliseconds < 1000` is always true,
I believe these should be `TotalMilliseconds` instead?
=> Use TotalMilliseconds instead of Milliseconds

src/xunit.console.nuspec, xunit.vs2017.sln
This adds a NuGet package for xunit.console.
This would be useful to us in the [dotnet/sdk](https://github.com/dotnet/sdk) and [dotnet/cli](https://github.com/dotnet/cli) repos.  It would allow the test projects to have a main method that calls into xunit.console, so tests could be run via `dotnet run`.  This makes it easier to attach a debugger to tests, since `dotnet test` and `dotnet xunit` both launch separate processes to run the tests.
=> Add NuGet package for xunit.console

src/xunit.runner.reporters/JsonExtentions.cs, test/test.xunit.runner.reporters/JsonExtensionsTests.cs
In Russian language evniropment default converter of double/float numbers uses comma (`,`), instead dot (`.`) and JSON will be incorrect. Example:
```
{
"message": "testPassed",
"flowId": "d2e1c4f6508847269e92603003bc8c5c",
"executionTime": 0,0519754,
"output": ""
}
```
How to reproduce:
```
> WriteLine(String.Format(@"""{0}"":{1}", "executionTime", 0.0519754.ToString(System.Globalization.CultureInfo.GetCultureInfo("ru-RU"))));
"executionTime":0,0519754
```
Correct code variant:
```
> WriteLine(String.Format(@"""{0}"":{1}", "executionTime", 0.0519754.ToString(System.Globalization.CultureInfo.InvariantCulture)));
"executionTime":0.0519754
```
=> [=] Fix incorrect json conversion of double/float numbers

src/xunit.core.nuspec, src/xunit.core/build/xunit.core.targets
This removes the hacks needed for UWP test platform v1 with the desktop adapter.
Also fixes 
```
/Users/.../.nuget/packages/xunit.core/2.4.0-beta.1.build3958/buildMultiTargeting/xunit.core.targets(23,11): error MSB4086: A numeric comparison was attempted on "$(UnitTestPlatformVersion)" that evaluates to "" instead of a number, in condition " '$(UnitTestPlatformVersion)' >= '15.5' ". [/Users/…/Git/…/src/Testing.Common/Testing.Common.csproj]
Build failed!
```
Since the current logic was assuming `VisualStudioVersion` being set
=> Remove UWP test platform v1 wokarounds. 

src/xunit.runner.visualstudio/VsTestRunner.cs, test/test.xunit.runner.visualstudio/RunnerReporterTests.cs
Following RFC: https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0020-Improving-Logic-To-Pass-Sources-To-Adapters.md
=> xunit.vs.runner to support managed sources only

test/test.xunit.assert/Asserts/CollectionAssertsTests.cs
Positive and negative case for each.
Implementation exists in https://github.com/xunit/assert.xunit/pull/24.
[#1620]
=> Adds Tests for Assert.Contains Overloads

src/dotnet-xunit/Program.cs, src/xunit.console/JUnitXml.xslt, src/xunit.console/Utility/TransformFactory.cs, src/xunit.console/xunit.console.csproj, src/xunit.runner.msbuild/xunit.cs
In #1200 XSL-T support was added. One feature request mentioned was support for generating JUnit XML files. This PR adds just that, following the instructions mentioned in that issue.
The transformation is largely based on https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html and http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd 
This should help support certain CI systems, in my case with BitBucket Pipelines which only accepts test files in this particular format.
=> Adding transformation for JUnit XML output, as documented in #1200.

src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs, src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunnerTests.cs, test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunnerTests.cs
Added possibility to use DiagnosticMessageSink in ClassFixture.
I also changed a little bit current implementation of CollectionFixture creation to meet more or less ClassFixtures mechanism
=> Allow to inject IMessageSink into ClassFixture/CollectionFixture (#565)

src/xunit.execution/Sdk/TypeUtility.cs, src/xunit.execution/xunit.execution.csproj
Fixes https://github.com/xunit/xunit/issues/1781
Fixes https://github.com/xunit/xunit/issues/1788
With netcoreapp2.1 we added implicit conversions between string and `ReadOnlySpan<char>` which are picked here and tried to be invoked. The execution fails as ByRefLike Types aren't currently supported to be invoked by `MethodInfo.Invoke`. The error currently doesn't happen on .NET Framework as we haven't yet added these implicit conversions there.
This approach uses reflection as the `Type.ByRefLike` property isn't exposed in .NET Standard. It will probably be included with .NET Standard vNext.
cc @jkotas @bradwilson @onovotny
=> Exclude byreflike types from type conversion

src/xunit.console/NUnitXml.xslt
The NUnit 2.5 schema at http://nunit.org/files/testresult_schema_25.txt specifies
that the test-case element should look like this:
```xml
<xs:complexType name="test-caseType">
<xs:sequence>
<xs:element name="categories" type="categoriesType" minOccurs="0" maxOccurs="1" />
<xs:element name="properties" type="propertiesType" minOccurs="0" maxOccurs="1" />
<xs:choice>
<xs:element name="failure" type="failureType" minOccurs="0" />
<xs:element name="reason" type="reasonType" minOccurs="0" />
</xs:choice>
</xs:sequence>
<xs:attribute name="name" type="xs:string" use="required" />
...
```
The usage of xs:sequence means categories, properties and failure/reason elements
need to be emitted in exactly that order.
Currently NUnitXml.xslt however emits the properties _after_ the reason element.
This …
=> Update NUnitXml.xslt to emit properties element before reason/failure

CONTRIBUTING.md
The link was pointing to an empty list of issues. The new link now shows all "Help Wanted" tagged issues.
=> Fixed "Help wanted" link in the Contributing.md

src/common/Json.cs
Fixes https://github.com/xunit/xunit/issues/1980
=> Fix IndexOutOfRange when parsing json string with unicode escaped characters

src/xunit.core/Sdk/DataDiscoverer.cs
since reflectionTestMethodType is always used. I would assume "non IReflectionTypeInfo" is not allowed since it would result in null ref. A cast is better since if it is incorrect an invalid cast will be easier to debug than a null ref
=> Use cast instead of as for IReflectionTypeInfo

src/xunit.console/JUnitXml.xslt
According to [schema](https://github.com/junit-team/junit5/blob/3804182b1c26cb724aab86ccde155cc61cffc9b1/platform-tests/src/test/resources/jenkins-junit.xsd#L76).
This is needed for tests to show correctly in GitLab CI: https://gitlab.com/gitlab-org/gitlab-ce/issues/50964.
=> Add classname attribute to testcase in JUnit XSLT

src/xunit.console/CommandLine.cs, src/xunit.console/ConsoleRunner.cs
This option makes the console runner wait for the user to press a key at start,
which makes it easy to attach a debugger to the test process.
=> Make available xunit.console pause option also in Release builds.

LICENSE, src/common/Annotations.cs, src/xunit.v3.assert/xunit.v3.assert.csproj, src/xunit.v3.core/Record.cs, src/xunit.v3.core/xunit.v3.core.csproj
Fixes #2011 and #2033.
There is a parallel PR that annotates `Assert.NotNull` in https://github.com/xunit/assert.xunit/pull/36.
The commit here enables NRT on two projects (`xunit.assert` and `xunit.core`), setting the language version to C# 8 on both. Ultimately it would probably make sense to enable it for all code in the repository, but it's prudent to roll it out in small steps such as this.
This requires Visual Studio 16.3 or later, or a new enough compiler. I expect this to PR to fail in various ways in CI, as this no doubt builds in environments where a new enough compiler is not available. In such cases it is possible to opt-in to a specific version of the compiler via its NuGet package. I'll see what happens in CI first.
I've been dogfooding NRT for a while now so am happy to …
=> Enable C# 8 Nullable Reference Types

global.json
MSBuild.Sdk.Extras 1.6.55 had this bug:
https://github.com/novotnyllc/MSBuildSdkExtras/issues/127
1.6.61 fixes it.
This fixes:
https://github.com/xunit/xunit/issues/1972
https://github.com/xunit/xunit/issues/1819
=> Fix build of the v2 branch.

src/xunit.v3.assert.tests/Asserts/StringAssertsTests.cs
Assert.Equal with ignoreWhiteSpace = true will now ignore
```
SPACE (U+0020)
NO-BREAK SPACE (U+00A0)
OGHAM SPACE MARK (U+1680)
MONGOLIAN VOWEL SEPARATOR (U+180E)
EN QUAD (U+2000)
EM QUAD (U+2001)
EN SPACE (U+2002)
EM SPACE (U+2003)
THREE-PER-EM SPACE (U+2004)
FOUR-PER-EM SPACE (U+2005)
SIX-PER-EM SPACE (U+2006)
FIGURE SPACE (U+2007)
PUNCTUATION SPACE (U+2008)
THIN SPACE (U+2009)
HAIR SPACE (U+200A)
ZERO WIDTH SPACE (U+200B)
NARROW NO-BREAK SPACE (U+202F)
MEDIUM MATHEMATICAL SPACE (U+205F)
IDEOGRAPHIC SPACE (U+3000)
ZERO WIDTH NO-BREAK SPACE (U+FEFF)
TABULATION \u0009
```
Includes the tests for [32](https://github.com/xunit/assert.xunit/pull/32).
As per [#1931](https://github.com/xunit/xunit/issues/1931).
=> Assert.Equal with ignoreWhiteSpace = true improvements

src/xunit.v3.core.tests/Sdk/Frameworks/XunitTestCaseTests.cs, src/xunit.v3.core/Sdk/Reflection/ReflectionAttributeInfo.cs
Fixes #1397 
The issue was caused due to `ITraitAttribute` using the default `AttributeUsageAttribute` (as it can't have one of its own, not being an actual `Attribute`), which means the `AllowMultiples` property is false.
This change adds a default `AttributeUsageAttribute` instance straight into the cache when it is initialised. `ConcurrentDictionary` does not work with collection initialisers, so I've added an `IEnumerable<KeyValuePair<Type, AttributeUsageAttribute>>` into the constructor. This is far from neat, so perhaps it would be better to add a static constructor to the `ReflectionAttributeInfo` class and seed the cache at that point?
Also, I have added unit tests to prove the fix, but these could do with some improvement too - I'm open to suggestions. The actual method that …
=> Fixes issue where traits cannot be inherited from multiple levels of inheritance.

src/xunit.v3.runner.common/Transforms/templates/NUnitXml.xslt
CI post-processing scripts may need the test method name; many tools use nunit-style output.
When the test is a Theory, the method name has to be parsed from test-case name. Much worse,
when xunit is used with TechTalk.SpecFlow, the test-case name is based on the Scenario name;
the method name is completely lost! Emit method name as property MethodName in nunit output.
=> Emit MethodName as a test-case property in -nunit output

src/messages/DiagnosticMessage.cs
My hope is that the diagnostics will become available in JetBrains Rider unit test logs. Currently, we can see messages like this: `TestRunner: XUnitRunner Xunit.Sdk.DiagnosticMessage`. My intuition is that the Rider test runner is calling `ToString()` on `Xunit.Sdk.DiagnosticMessage` and that implementing `ToString()` will get the actual diagnostic messages in the Rider logs.
Anyway, implementing `ToString()` in a class that wraps a message string can't hurt.
```
09:14:44.304 |I| TestRunner: XUnitRunner Execution started 
09:14:44.310 |I| TestRunner: Discoverer Discovering tests from ~/Projects/MyApp/MyApp.Tests/bin/Debug/netcoreapp3.1/MyApp.Tests.dll 
09:14:44.550 |V| TestRunner: Discoverer Sending discovery results to server... 
09:14:44.602 |V| Run: …
```
=> Implement ToString on DiagnosticMessage

docs/capturing-output.html
Fixes #2218, added alphabetically.
=> Add IClassFixture to 'Capturing output in extensibility classes' list

src/xunit.v3.runner.common/Loggers/ConsoleRunnerLogger.cs
Hello,
While I was looking for a cause of https://github.com/xunit/xunit/issues/2227, I've noticed that the console colors changes are not part of the lock, which will cause the colors to be mixed together.
I believe this would also potentially cause invalid escape codes to be emitted, but I am not sure if it could generate codes that can cause a previous character (the newline) to be lost).
I thought it was worth it to raise this small PR even if it has not been discussed yet in the issue.
There are currently not test and would not be easy to write one for this problem, so I haven't added one.
Please let me know what do you think.
Thank you,
Alessio
=> Fix Console colors concurrency handling

docs/comparisons.markdown
The sentence:
> xUnit.net ships with support for data-driven tests call Theories
Should read:
> xUnit.net ships with support for data-driven tests **called** Theories
=> Fix typo in comparisons.markdown

docs/getting-started/netcore/visual-studio.html
The sentence:
> In the drop down boxes, chooses your language (C#)...
Should read:
> In the drop down boxes, **choose** your language (C#)...
=> Fix typo in visual-studio.html

docs/running-tests-in-parallel.html
The following sentence:
> There are several default pieces of behavior that be configured by the...
Should read:
> There are several default pieces of behavior that **can** be configured by the...
=> Fix typo in running-tests-in-parallel.html

docs/running-tests-in-parallel.html
The following sentence:
> ...and command line options can be used to configuration the parallelism options...
Should read:
> ...and command line options can be used to **configure** the parallelism options...
=> Fix another typo in running-tests-in-parallel.html

docs/shared-context.html
The following sentence:
> Just before the first tests in MyDatabaseTests is run...
Should read:
> Just before the first test in MyDatabaseTests is run...
The following sentence:
> ...share a single object instance among tests in several test class.
Should read:
> ...share a single object instance among tests in several test classes.
=> Fix typos in shared-context.html

src/xunit.execution/Sdk/DisposalTracker.cs
Proposed fix for (v2 branch): https://github.com/xunit/xunit/issues/1855
Fixes: https://github.com/dotnet/runtime/issues/11063 (this fix would help improve the test pass rate in dontet/runtime infra.)
Opened in lieu of initial PR: https://github.com/xunit/xunit/pull/2375.
---
* Cherry pick from v3 of eacf435.
A couple notes:
- I applied a cherry pick to preserve history of where the fix is coming from even though the v3 change is on a different file.
- The original commit that was cherry picked is nullable annotated but the v2 version is not.
- The original commit had the `isDisposed` flag and v2 doesn't have that flag.
- The original commit does not have a call to `toDispose.Clear()` in `Dispose()` but v2 has.
We left the test (linked …
=> Add lock around DisposalTracker

src/xunit.runner.reporters/TeamCityReporterMessageHandler.cs, test/test.xunit.runner.reporters/TeamCityReporterMessageHandlerTests.cs
When running tests in parallel, we faced two issues, the output didn't seem to match the test in TeamCity, and we were unable to include extra service messages to add metadata to the test (like a link).
Including these extra parameters allowed us to implement this.
Fixes: https://github.com/xunit/xunit/issues/2397
=> Include flowId and parseServiceMessages for stdOut

src/xunit.runner.utility/Utility/ConsoleRunnerLogger.cs
Hi Brad, 
as the bug fixed in https://github.com/xunit/xunit/pull/2228 is also present on v2, it would be nice to backport it.
However not sure on what is the current policy and process for v2 bug fixes, so let me know if this is not the desirable action.
Thank you,
Alessio
=> Backport: Fix Console colors concurrency handling

docs/capturing-output.html
Fix #2136 
Change preview when running gh-pages locally:
=> Add information about console output logging

src/xunit.v3.common/Utility/TypeUtility.cs, src/xunit.v3.core.tests/Acceptance/Xunit3TheoryAcceptanceTests.cs
`TypeUtility.PerformDefinedConversions` now handles the case where there are multiple `op_Implicit` or `op_Explicit` methods that take the same parameter type.
Add tests to validate those conflicting cases, using `Decimal`-to-`int` and `int`-to-`Decimal` conversions.
Closes #2418
=> PerformDefinedConversions handles multiple conflicting conversions

src/xunit.v3.assert.tests/Asserts/CollectionAssertsTests.cs
Test for https://github.com/xunit/assert.xunit/pull/48
Issue https://github.com/xunit/xunit/issues/2402
Ensure that Assert.Equals on IEnumerables will only enumerate once.
=> Test that Equals only enumerates once

README.md
The link worked if you were on https://xunit.net, but clicking it from the README on GitHub would take you to the non-existent https://github.com/xunit/xunit/blob/main/docs/v3-alpha
=> Fix link for v3 alpha docs

xunit.analyzers/_rules/xUnit2014.md
While the suggested fix is correct (it replaces `Assert.Throws` with `Assert.ThrowsAsync` to fix the violation), it also renders this assert useless (the suggested test will give false positives if the type of the actual exception doesn't match the type of the expected exception).
=> Add async-await to the suggested fix in xUnit2014 analyzer rule documentation

src/xunit.v2.tests/Sdk/Frameworks/Runners/XunitTestAssemblyRunnerTests.cs, src/xunit.v3.core.tests/Sdk/v3/Runners/XunitTestAssemblyRunnerTests.cs
Hi! I love xunit, and I want to help you :)
This commit clean your code, because this code not used, above this code we already have a null check:
``` cs
if (testCases == null)
testCases = new[] { Mocks.XunitTestCase<ClassUnderTest>("Passing") };
```
and this code - not used:
``` cs
testCases ?? new IXunitTestCase[0]
```
I hope it's helpful!
=> Delete useless null checks in testCases

docs/why-did-we-build-xunit-1.0.markdown
Fix "change that we wanted to affect" to "change that we wanted to
effect". "Affect change" is a common misspelling of "effect change". [1]
[1] https://writingexplained.org/affect-change-or-effect-change
=> Docs: fix typo in "Why did we build XUnit 1.0" page

build
allow use windows bash, since powershell is often blocked
=> allow bash on windows

src/xunit.v3.assert.tests/Asserts/Sdk/ArgumentFormatterTests.cs
Fix for https://github.com/xunit/xunit/issues/2534
Is this issue still open? Saw there was a pull request a while aga.
I tested it and it works, however it doesn't have a call to IsSZArray as requested in Sample Fix and isn't implemented as an extension method to work downlevel.
Anyway I made a fix for the issue that makes a call to IsSZArray and also works downlevel incase IsSZArray is not available due to .NET Version
Let me know what you think of the fix. And if any further improvements are required.
PS: there was a separate pull request for the submodule
=> #2534 Fix: "ArgumentFormatter doesn't pretty-print rank-1 variable-bound arrays correctly"

src/xunit.v3.core.tests/Sdk/Frameworks/DisplayNameFormatterTests.cs, src/xunit.v3.core/Sdk/Frameworks/DisplayNameFormatter.cs
I implemented a look-ahead method on the `FormatContext`. This allows the implementation to consume the whole escape sequence at once or not at all. This should fix #2651.
=> #2651 Fix unicode escaping of test names.

build.ps1
Some time ago I started [this discussion](https://github.com/dotnet/runtime/discussions/84764). Current PR fixes problem with invalid parsing .NET preview version format in AutoMapper build script.
=> Extending build script for working with preview .NET versions.

src/xunit.assert.nuspec, src/xunit.assert.source.nuspec, src/xunit.console.nuspec, src/xunit.core.nuspec, src/xunit.extensibility.core.nuspec, src/xunit.extensibility.execution.nuspec, src/xunit.nuspec, src/xunit.runner.console.nuspec, src/xunit.runner.msbuild.nuspec, src/xunit.runner.reporters.nuspec, src/xunit.runner.utility.nuspec
Fixes #2742
Added `releaseNotes` to nuspec files for projects mentioned on https://xunit.net/releases/2.5.0:
* xunit
* core
* assert
* extensibility
* runners
One downside (mostly for pre-release packages) is that this will generate a link in NuGet to a page that may not ever exist, e.g., https://xunit.net/releases/2.5.1-pre.2.
=> Add release notes link to nuspec files

src/xunit.v3.core.tests/Acceptance/Xunit3TheoryAcceptanceTests.cs, src/xunit.v3.core/MemberDataAttribute.cs, src/xunit.v3.core/MemberDataAttributeBase.cs, src/xunit.v3.core/Sdk/MemberDataDiscoverer.cs
Proposed fix for https://github.com/xunit/xunit/issues/1985
@bradwilson 
=> Allow for MemberData to not specify arguments for optional parameters

xunit.analyzers/_rules/xUnit1031.md
Added disabled parallelization section to give users a guide on how to disable this warning when parallelization is disabled
=> Added Disabled Parallelization section to xUnit1031 warning documentation

src/xunit.v3.runner.common/Configuration/ConfigReader_Json.cs, src/xunit.v3.runner.common/Parsers/CommandLineParserBase.cs, src/xunit.v3.runner.console/CommandLine.cs, src/xunit.v3.runner.console/ConsoleRunner.cs, src/xunit.v3.runner.inproc.console/CommandLine.cs, src/xunit.v3.runner.inproc.console/ConsoleRunner.cs, src/xunit.v3.runner.msbuild/xunit.cs, src/xunit.v3.runner.tdnet/TdNetRunnerHelper.cs, src/xunit.v3.runner.utility.tests/Configuration/ConfigReaderTests.cs, src/xunit.v3.runner.utility/Configuration/ConfigReader.cs, src/xunit.v3.runner.utility/Configuration/ConfigReader_Configuration.cs, src/xunit.v3.runner.utility/Runners/AssemblyRunner.cs
v3 support #1655 (and supercedes #2434)
As discussed in the issue, I did the changes for the v3 api and then implemented them to the IRunnerLogger whenever the runner supported it. This also includes amending the existing unit tests. I had to change the 2 CommandLine class due to the need of having to parse, store the warnings and then later log them, not sure if this is a problem, but we can discuss if it is.
The warnings I put are the following:
- The file was sent explicitly, but it wasn't a .json / .config file or doesn't exist (no warning if no filename was sent)
- The file exists, but the root object isn't a json one
- The file exists, but it failed to read
- The file exists, was read, but the deserialisation failed
Let me know if this is exhaustive, I tried to cover all the runners …
=> Emit warning messages to the runner for config files when relevant

src/xunit.v3.core/TheoryData.cs
Fix typo in `TheoryData<T>` constructors I spotted in VS IntelliSense.
=> Fix typos in XML documentation

src/xunit.v3.templates/templates/project/xunit3-extension/fs/SupportedOSAttribute.fs
In response to https://elk.zone/mastodon.social/@bradwilson/112865921926948375:
- Use Map.tryFind rather than IDictionary method
- Fix setting mutable value
- Avoid constructing Exception objects by using `invalidArg` and `failwith`
For lightly more idiomatic FSharp I might have replaced the `for` loop with a tail recursive function, but exceptions are being used in control flow I don't think it makes much difference.
=> Update/fix FSharp SupportedOSAttribute project template

src/xunit.runner.reporters/TeamCityReporterMessageHandler.cs, test/test.xunit.runner.reporters/TeamCityReporterMessageHandlerTests.cs
Request fixes this issue https://github.com/xunit/visualstudio.xunit/issues/394
The output name of the test suites does not need a flow id.
I can assume that during the development of xunit.runner.visualstudio 2.5 version, flow id generation for test suites was fixed, which caused test suites to stop being constant, which breaks the history of test execution on Teamcity.
=> TeamCity Reporter. Remove flow id from name of test suites.

src/xunit.v3.core/Abstractions/Attributes/IFactAttribute.cs, src/xunit.v3.core/Attributes/MemberDataAttributeBase.cs, src/xunit.v3.core/MemberDataAttribute.cs
This fixes #2991 
- **MemberDataAttribute**: Updated XML documentation for the `memberName` parameter to recommend using the `nameof` operator for compile-time safety.
- **SkipWhen**: Updated XML documentation to suggest the use of `nameof` for referencing public static properties to ensure safer and more maintainable code.
- **SkipUnless**: Added a recommendation in the XML documentation to use the `nameof` operator when referencing public static properties, promoting best practices.
=> added recommendation to use nameof

site/docs/getting-started/v3/whats-new.md
The `.md` extension on those links end up showing the 404 page in GitHub pages:
- <https://xunit.net/docs/getting-started/v3/whats-new.md> vs <https://xunit.net/docs/getting-started/v3/whats-new>.
- <https://xunit.net/docs/query-filter-language.md> vs <https://xunit.net/docs/query-filter-language>
=> Fix internal links

src/xunit.v3.assert.tests/xunit.v3.assert.tests.csproj, src/xunit.v3.assert.x86.tests/xunit.v3.assert.x86.tests.csproj, src/xunit.v3.assert/xunit.v3.assert.csproj, src/xunit.v3.assert/xunit.v3.assert.nuspec
The "System.Collections.Immutable" and "System.Memory" packages are built-in to .NET 8, so referencing them when targeting .NET 8 just gives users unnecessary transitive package references.
=> Reference .NET built-in packages conditionally

site/docs/query-filter-language.md
This must be a recent development, as comments on issues also use the `--query-filter`, but in the logs of a failed run it clearly shows all the available switches as `--filter-xyz`, so I imagine this was just normalized at some point.
Will do a scan elsewhere too
=> Docs should use  `--filter-query` instead of `--query-filter`

src/xunit.v3.runner.inproc.console/TestingPlatform/TestPlatformExecutionMessageSink.cs
This prevents file names with double extensions (e.g. screenshot.png.png) if the attachment name already contains a file extension.
=> Avoid duplicating file extensions in attachment file names

src/xunit.v3.core/TestContext.cs
@bradwilson You better know how things flow in xunit. I'm wondering if this could be causing some memory leaks. For winforms, I still see memory leaks:
I wonder if this CTS which is not being disposed is the issue here?
=> Dispose CTS in TestContext
