- src/xunit.runner.reporters/AppVeyorClient.cs
Related discussion on AppVeyor forums: http://help.appveyor.com/discussions/problems/3940-appveyor-test-service-erroring
> Increase request timeout in AppVeyorClient

- src/common/XmlTestExecutionVisitor.cs
- test/test.xunit.execution/Common/XmlTestExecutionVisitorTests.cs
- test/test.xunit.execution/Sdk/ArgumentFormatterTests.cs
This pull request add tests for the changes introduced in xunit/assert.xunit#1 and xunit/assert.xunit#2. It also fixes the original issue as defined in #804, and updates the Git submodule for Asserts.
cc @bradwilson
> Further fix handling of invalid chars + add tests

- README.md
http://xunit.github.io ->https://xunit.github.io for better security.
> [README.md] Update link to use HTTPS

- src/xunit.runner.utility/Sinks/DelegatingSinks/DelegatingXmlCreationSink.cs
in DelegatingXmlCreationSink.CreateTestResultElement().
Rationale:
I did profiling of latest xunit bits from the myget feed, with the msbuild runner, and found that 4.3% of CPU samples were used in CreateTestResultElement, and most of that is used up on TransparentProxyStub_CrossContext.
I think this change should cut down on the number of cross-context calls.
> Cache objects which might have to be retrieved across remoting boundaries

- test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunnerTests.cs
Relies on xunit/assert.xunit#5
@bradwilson
> Add tests for throwing enumerator/tostring in argument formatting

- src/common/XunitSerializationInfo.cs
- test/test.xunit.execution/Common/XunitSerializationInfoTests.cs
> Fix serialization and deserialization of negative zero doubles/floats

- src/common/XunitSerializationInfo.cs
- test/test.xunit.execution/Common/XunitSerializationInfoTests.cs
Fixes #675
Fixes #826
@ayb4btu @Ausm @ljani FYI
> Add support for serializing multidimensional arrays

- src/xunit.runner.utility.nuspec
- src/xunit.runner.utility/Configuration/ConfigReader_Json.cs
- src/xunit.runner.utility/Frameworks/VisualStudioSourceInformationProvider.cs
- src/xunit.runner.utility/Frameworks/XunitFrontController.cs
- src/xunit.runner.utility/Utility/DiaSession.cs
- src/xunit.runner.utility/Utility/DiaSessionWrapperHelper_DotNet.cs
- src/xunit.runner.utility/Utility/DiaSessionWrapper_DotNet.cs
- src/xunit.runner.utility/project.json
Fixes #1054 by providing a version of the runner utility that supports DiaSession:
After this is merged, the visual studio runner needs to use this updated version of the utility. In the interim, manually specifying the package works.
> Enable a NETStandard 1.5 version that includes support for DiaSession

- src/xunit.runner.utility/Sinks/DelegatingSinks/DelegatingLongRunningTestDetectionSink.cs
> Fix exception caused by not having a lock

- test/test.xunit.assert/Asserts/CollectionAssertsTests.cs
See https://github.com/xunit/assert.xunit/pull/9
> Add tests for included collection in Assert.Collection failure

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
https://github.com/xunit/assert.xunit/pull/6
> Add tests for improved Assert.Equal behaviour for different types

- src/xunit.console/Program.cs
I tried all of these, and eventually had to look at this source file just to see how to get help...
> Add a few ways to show the usage message

- src/xunit.runner.msbuild/xunit.cs
Proactively created this PR since its a very simple change.
IgnoreFailures needs to have a public setter. Fixes #1076
> Fixes #1076 - public setter for IgnoreFailures

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
Tests/relies on xunit/assert.xunit#10
See xunit/xunit#1090
> Add tests for differing generic ISets

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
Tests for xunit/assert.xunit#11
> Add tests for IComparable equality assertions of different types

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
Tests for xunit/assert.xunit#12
> Add tests for IEquatable<T> and IComparable<T> for Assert.Equal<T>

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
Tests for xunit/assert.xunit#13
> Add tests for Assert.Equals with IComparable<T> throwing

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
Tests for xunit/assert.xunit#14
> Add tests for Assert.Equal with IStructuralEquatable

- src/xunit.runner.reporters/AppVeyorReporterMessageHandler.cs
> Ensure AppVeyor reporter can handle test assembly parellelism

- test/test.xunit.assert/Asserts/CollectionAssertsTests.cs
Tests for xunit/assert.xunit#15
> Update tests for including the collection in Assert.Empty

- test/test.xunit.assert/Asserts/EqualityAssertsTests.cs
Tests for xunit/assert.xunit#17
> Add tests for Assert.Equal with IEquatable<typeof(actual>) and IComparable<typeof(actual)>

- src/xunit.core/TheoryData.cs
Added TheoryData types with 6, 7, 8, 9 and 10 parameters.
> Added TheoryData types with 6, 7, 8, 9 and 10 parameters

- test/test.xunit.assert/Asserts/CollectionAssertsTests.cs
> Add unit tests for Assert.Contains changes at xunit/assert.xunit#20

- src/xunit.core/MemberDataAttributeBase.cs
- test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs
> Support value types/ienumerable in MemberDataAttributeBase

- src/xunit.runner.msbuild/xunit.cs
> Close `Xml` result file as soon as possible

- src/dotnet-xunit/Program.cs
- src/xunit.console/ConsoleRunner.cs
Following up on https://github.com/xunit/xunit/pull/766 (allowing wildcards)
> Update usage information for -method

- src/xunit.execution/Sdk/Reflection/Reflector.cs
- test/test.xunit.execution/Sdk/Reflection/ReflectorTests.cs
I was going to [add this to xbehave](https://github.com/xbehave/xbehave.net/issues/155), but then I thought I'd speculate on whether you'd want it in xunit (xbehave would inherit the feature with no work).
> Conversion of strings to Guid and DateTime argument values

- appveyor.yml
- build.ps1
- tools/SignClient/appsettings.json
> Use SignService v2

- src/xunit.runner.reporters/TeamCityReporterMessageHandler.cs
- test/test.xunit.runner.reporters/TeamCityReporterMessageHandlerTests.cs
A fix for https://github.com/xunit/xunit/issues/1185 with some performance tweak as well
> Escape utf8 characters in teamcity output

- src/xunit.execution/Sdk/TypeUtility.cs
- test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs
This resolves https://github.com/xunit/xunit/issues/1607
> Support implicit & explicit conversions declared on the argument's type

- src/xunit.runner.utility/Configuration/ConfigReader_Json.cs
- test/test.xunit.runner.utility/Common/ConfigReaderTests.cs
- test/test.xunit.runner.utility/ConfigReader_NegativeThreads.config
- test/test.xunit.runner.utility/ConfigReader_NegativeThreads.json
https://github.com/xunit/xunit/issues/1629
> Fix Json config to honor -1 maxParallelThreads

- build.ps1
- global.json
- src/xunit.runner.utility/xunit.runner.utility.csproj
- src/xunit.runner.visualstudio/Constants.cs
- src/xunit.runner.visualstudio/Utility/RunSettings.cs
- src/xunit.runner.visualstudio/VsTestRunner.cs
- src/xunit.runner.visualstudio/xunit.runner.visualstudio.csproj
- test/test.harness.uwp/test.harness.uwp.csproj
- xunit.vs2017.sln
Should fix https://github.com/xunit/xunit/issues/1665
> UWP clean-up. Split executor URI and platform detect

- src/xunit.runner.visualstudio/VsTestRunner.cs
> fixes CS8363

- src/xunit.runner.utility/Frameworks/XunitFrontController.cs
Faster for directories with many files.
Signed-off-by: Levente Koncz <Levente.Koncz@sapagroup.com>
> Use lazy enumeration of files in directory in: XunitFrontController.

- NuGet.Config
This fixes the error the msbuild /restore gives (at least with VS 15.8).
> Use HTTPS for package sources

- src/dotnet-xunit/Program.cs
- src/xunit.console/CommandLine.cs
- src/xunit.console/ConsoleRunner.cs
- src/xunit.runner.utility/Project/XunitFilters.cs
Fixes #1701. 
Mirror the implementation for including and excluding methods, classes and namespaces.
cc @ViktorHofer
> Add Test Case Exclusions

- src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs
- test/test.xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunnerTests.cs
> First dispose async and then usual dispose #1749

- test/test.xunit.assert/Asserts/ExceptionAssertsTests.cs
> Update ref in assert.xunit repo

- global.json
> Update the SDK extras version

- src/xunit.console/CommandLine.cs
- src/xunit.console/Utility/TransformFactory.cs
Related to #1816, I thought I'd try starting to contribute with something small.
Also an opportunity for feedback. Thanks
> #1816 Error message doesn't respect -nocolor option

- src/xunit.execution/Sdk/TypeUtility.cs
- test/test.xunit.execution/Acceptance/Xunit2TheoryAcceptanceTests.cs
- test/test.xunit.execution/ResolveGenericMethodTests.cs
Port from @hughbe's change: https://github.com/xunit/xunit/pull/1812 to v2 + feedback.
> Fix generic oversight v2

- src/xunit.runner.msbuild/xunit.cs
> Fix JUnit transformation from MSBuild

- src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs
- src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs
> remove a couple of redundant state machines

- xunit.vs2017.sln
> remove dotnet-xunit.nuspec from sln

- src/common/AssemblyResolution/Microsoft.Extensions.DependencyModel/Dependency.cs
- src/common/AssemblyResolution/Microsoft.Extensions.DependencyModel/DependencyContextJsonReader.cs
- src/common/ExceptionExtensions.cs
- src/common/ExceptionUtility.cs
- src/common/Json.cs
- src/common/SerializationHelper.cs
- src/common/XunitSerializationInfo.cs
- src/xunit.core/ClassDataAttribute.cs
- src/xunit.core/MemberDataAttribute.cs
- src/xunit.core/MemberDataAttributeBase.cs
- src/xunit.core/Sdk/DataDiscoverer.cs
- src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs
- src/xunit.execution/Sdk/ExtensibilityPointFactory.cs
- src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs
- src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs
- src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs
- src/xunit.execution/Sdk/Frameworks/TheoryDiscoverer.cs
- src/xunit.execution/Sdk/Messages/DelegatingMessageBus.cs
- src/xunit.execution/Sdk/Messages/DelegatingMessageSink.cs
- src/xunit.execution/Sdk/Reflection/ReflectionAttributeInfo.cs
- src/xunit.execution/Sdk/TestDiscoveryVisitor.cs
minor perf improvement, and less code
> remove some redundant type checking

- src/xunit.core/TheoryData.cs
> Fixed class descriptions.

- docs/running-tests-in-parallel.html
> Fix syntax error in documentation

- src/xunit.v3.core.tests/Acceptance/CollectionAcceptanceTests.cs
- src/xunit.v3.core.tests/Acceptance/Xunit2AcceptanceTests.cs
- src/xunit.v3.core.tests/Sdk/Frameworks/Runners/XunitTestCaseRunnerTests.cs
- src/xunit.v3.core/Sdk/BeforeAfterTestAttribute.cs
- src/xunit.v3.core/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs
Figured it would be easier to resubmit
> add assembly level BeforeAfterAttributes

- docs/ms-test-migration.html
- index.html
> Add page Migrating from MSTest to xUnit.net

- src/xunit.v3.core.tests/Common/TraitHelperTests.cs
- src/xunit.v3.core/Sdk/TraitHelper.cs
> Add tests and fix for recursive trait discovery.

- docs/getting-started/netcore/cmdline.html
Hello xUnit maintainers 👋
I think there is a missing word in the modified paragraph, please let me know if it was supposed to be like that.
Thanks in advance, have a great rest of the day.
> Add missing word "A good example of this testing..."

- src/xunit.v1.tests/xunit.v1.tests.csproj
- src/xunit.v3.assert.tests/Asserts/CollectionAssertsTests.cs
- src/xunit.v3.runner.utility.tests/xunit.v3.runner.utility.tests.csproj
Closes #2155 
Requires changes from https://github.com/xunit/assert.xunit/pull/42
> Add test to validate new dictionary output format

- src/xunit.v3.assert.tests/Asserts/EventAssertsTests.cs
Yes
Yes
I think so.
Updated the existing ones to make them generic.
It needs submodule update to go in first for successful build. https://github.com/xunit/assert.xunit/pull/43
> Unit tests added for EventAsserts.cs

- src/xunit.v3.assert.tests/Asserts/EqualityAssertsTests.cs
Yes
Yes
I think so
Yes
Part of solution to #1293.
Unit tests for [assert.xunit#44](https://github.com/xunit/assert.xunit/pull/44), the submodule will need to be updated for these tests to pass.
> Add unit tests for double equality with tolerance

- src/xunit.v3.assert.tests/Asserts/EqualityAssertsTests.cs
Yes
Yes
Yes
Yes
Requires [assert.xunit#45](https://github.com/xunit/assert.xunit/pull/45).
Fixes #1984.
> Add unit tests for float equality with tolerance

- src/xunit.v3.common/Utility/ExceptionUtility.cs
> Fix Assert.Throws double stacktrace

- src/xunit.v3.assert.tests/Asserts/CollectionAssertsTests.cs
See https://github.com/xunit/assert.xunit/pull/35
> Add tests for Assert.Distinct method

- src/xunit.v3.assert.tests/Asserts/SpanAssertsTests.cs
- src/xunit.v3.assert.tests/Asserts/StringAssertsTests.cs
Add testing for new Equals() flag ignoreAllWhiteSpace in assert.xunit. 
PR for issue [assert/#2440](https://github.com/xunit/xunit/issues/2440).
Submodule PR [assert.xunt/pull/51](https://github.com/xunit/assert.xunit/pull/51).
> Add testing for ignoreAllWhiteSpace flag on String & Span<char> Equal()

- xunit.analyzers/_rules/xUnit1014.md
> Removed unmatching string literal

- src/xunit.v3.core.tests/Sdk/TestOutputHelperTests.cs
- src/xunit.v3.core/Sdk/Frameworks/TestOutputHelper.cs
- src/xunit.v3.runner.common.tests/Logger/ConsoleRunnerLoggerTests.cs
- src/xunit.v3.runner.common/Loggers/ConsoleRunnerLogger.cs
- src/xunit.v3.runner.common/xunit.v3.runner.common.csproj
> Add support for ANSI-SGR sequences to console-output

- .github/workflows/pull-request.yaml
- .github/workflows/push-main.yaml
Testing PR actions with updated dependencies
> Update Actions dependencies

- src/xunit.v3.common.tests/Serialization/SerializationHelperTests.cs
- src/xunit.v3.common/Serialization/SerializationHelper.cs
fixes https://github.com/xunit/xunit/issues/2640 for v3
version for v2 here: https://github.com/xunit/xunit/pull/2641
> Add support for TimeSpan, BigInteger, TimeOnly, DateOnly

- src/xunit.v2.tests/Acceptance/Xunit2TheoryAcceptanceTests.cs
Reason of current PR is the same as [83a532d7373d1e2462a68caba5576a9d1c8641e3](https://github.com/xunit/xunit/commit/83a532d7373d1e2462a68caba5576a9d1c8641e3) for #2435
> Fix culture specific build fail.

- src/common.tests/TestDoubles/Mocks.Attributes.cs
- src/xunit.v3.common/Utility/DisposalTracker.cs
- src/xunit.v3.core.tests/Acceptance/Xunit3TheoryAcceptanceTests.cs
- src/xunit.v3.core.tests/Sdk/Frameworks/TheoryDiscovererTests.cs
- src/xunit.v3.core/ClassDataAttribute.cs
- src/xunit.v3.core/InlineDataAttribute.cs
- src/xunit.v3.core/MemberDataAttributeBase.cs
- src/xunit.v3.core/Sdk/ClassDataDiscoverer.cs
- src/xunit.v3.core/Sdk/DataAttribute.cs
- src/xunit.v3.core/Sdk/DataDiscoverer.cs
- src/xunit.v3.core/Sdk/Frameworks/TheoryDiscoverer.cs
- src/xunit.v3.core/Sdk/IDataDiscoverer.cs
- src/xunit.v3.core/Sdk/InlineDataDiscoverer.cs
- src/xunit.v3.core/Sdk/MemberDataDiscoverer.cs
- src/xunit.v3.core/Sdk/v3/Runners/XunitDelayEnumeratedTheoryTestCaseRunner.cs
Attempting to address https://github.com/xunit/xunit/issues/2162
@bradwilson
> First cut at allowing ClassDataAttribute marked classes to be disposed

- src/xunit.v3.assert.tests/Asserts/EquivalenceAssertsTests.cs
Fixes https://github.com/xunit/xunit/issues/2974
> Assert.Equivalent behaves incorrectly with Guid values

- site/docs/shared-context.html
A small mention of `IAsyncLifetime` in the doc.
> Added info about async setup/cleanup

- src/xunit.v3.assert.tests/Asserts/MultipleAssertsTests.cs
tests for the: [#3209](https://github.com/xunit/xunit/issues/3209)
> Add assert multiple async 3209

- src/xunit.v3.common/Options/ParallelAlgorithm.cs
Just a single word spelling correction in documentation
> Correct spelling in ParallelAlgorithm.cs

- src/Versions.props
Keeping dependencies up-to-date :)
> Update MTP to 1.7.3

- src/Versions.props
> Update MTP to 1.9.0
